Hide miner and resources pages.
iron-fish/wallet-app pull request #106
Opened 2022-11-16 13:49 UTC by azhurauski-sc

2022-11-16 13:59 UTC, skylarrichard123 approved these changes

2022-11-16 14:00 UTC, skylarrichard123 commented
Approving but im hoping the resources page does end up being created.

2022-11-17 05:02 UTC, ndemidovich-sc requested changes
I suggest to comment line with Miner Route in `App.tsx`

2022-11-17 07:57 UTC, azhurauski-sc commented
> Approving but im hoping the resources page does end up being created.

Sure but while it has no content it can be hidden, it will be easy to show it when it will be ready.

2022-11-17 08:00 UTC, ndemidovich-sc approved these changes

2022-11-17 08:42 UTC, merged