Update transaction status colors.
iron-fish/wallet-app pull request #147
Opened 2023-01-05 15:29 UTC by azhurauski-sc

2023-01-06 13:04 UTC, ndemidovich-sc reviewed
May be better to display `UNKNOWN` and `AWAIT_CONFIRMATIONS` statuses as `PENDING`?

2023-01-06 15:02 UTC, skylarrichard123 requested changes
This is my fault.
Could we change the dark mode background color for the sent txn from what it is now to #3E251B

2023-01-06 15:27 UTC, azhurauski-sc commented
Updated sent color.
UNKNOWN and AWAIT_CONFIRMATIONS statuses displayed as PENDING.

2023-01-10 04:13 UTC, ndemidovich-sc approved these changes

2023-01-10 14:29 UTC, skylarrichard123 approved these changes

2023-01-11 09:57 UTC, merged