Added fee estimation options.
iron-fish/wallet-app pull request #149
Opened 2023-01-10 14:04 UTC by azhurauski-sc

2023-01-10 14:21 UTC, skylarrichard123 requested changes
Can we make it so that once a send amount is added, the estimated fee field is populated with 'average'? 

Send amount in my opinion is the only thing that should be required before showing a fee.

2023-01-11 17:41 UTC, skylarrichard123 requested changes
Sorry, maybe my comments didn't make sense.

What I meant was that once a user adds an amount in the "I want to send" field, it would then automatically turn the fee to a resting state selected as 'average' .

2023-01-13 13:57 UTC, skylarrichard123 approved these changes

2023-01-18 05:04 UTC, ndemidovich-sc approved these changes

2023-01-19 12:04 UTC, merged