Added loading snapshot flow.
iron-fish/wallet-app pull request #150
Opened 2023-01-11 06:11 UTC by ndemidovich-sc

2023-01-18 05:11 UTC, ndemidovich-sc commented
@skylarrichard123 You can use this demo as base point for Snapshot UI.

2023-01-18 14:54 UTC, skylarrichard123 commented
We will detect whether or not the snapshot should be downloaded automatically, so the user won't have a choice in the flow. The reason being is this app is meant for people with lower tech savvy, so that might be a point of confusion for a lot of users.

2023-03-07 13:55 UTC, azhurauski-sc reviewed
some suggestions

2023-03-08 15:07 UTC, skylarrichard123 requested changes
Change requests here:
https://www.figma.com/file/fYw3aNgfS0qCS2jezGqv8P/Wallet-(New-Ui-Kit)?node-id=5000%3A21269&t=gZpgFbCkitM07Q7s-1

2023-03-09 07:08 UTC, azhurauski-sc commented on src/components/Snapshot/SnapshotStatusModal.tsx
> +              <Progress
there are two variants available `ironBlue` and `ironLightBlue` for Progress

2023-03-20 14:05 UTC, merged