Added address column for peers.
iron-fish/wallet-app pull request #168
Opened 2023-02-02 07:39 UTC by ndemidovich-sc

2023-02-02 08:30 UTC, azhurauski-sc approved these changes

2023-02-02 19:51 UTC, skylarrichard123 commented
<img width="902" alt="Screen Shot 2023-02-02 at 2 50 54 PM" src="https://user-images.githubusercontent.com/75860817/216435048-141acbfa-620c-4591-a738-f60f25a39014.png">
<img width="707" alt="Screen Shot 2023-02-02 at 2 51 08 PM" src="https://user-images.githubusercontent.com/75860817/216435080-92a890b8-288f-4c31-8680-08a92c54d0c3.png">

2023-02-02 19:51 UTC, skylarrichard123 requested changes
Can we distribute these columns more evenly?

2023-02-03 14:55 UTC, ndemidovich-sc commented
> Can we distribute these columns more evenly?

Fixed.

2023-02-06 16:50 UTC, skylarrichard123 approved these changes

2023-02-07 05:56 UTC, merged