(IRO-2655) Added sync warning message.
iron-fish/wallet-app pull request #69
Opened 2022-10-07 11:46 UTC by azhurauski-sc

2022-10-07 14:21 UTC, skylarrichard123 requested changes
I think it needs to stay until someone clicks the X button.

2022-10-10 06:02 UTC, ndemidovich-sc requested changes
Please add usage of Demo Data Manager.
You can use as example current implementation of [`NodeStatus` from `rpc` module at `ironfish`](https://github.com/iron-fish/ironfish/blob/d66edb4e6ff4b60a483c591eb450ddfd8ac8094b/ironfish/src/rpc/routes/node/getStatus.ts#L40) lib.

2022-10-12 17:14 UTC, skylarrichard123 commented
There's no preview link @ndemidovich-sc

2022-10-12 17:23 UTC, azhurauski-sc commented
> There's no preview link @ndemidovich-sc

Fixed

2022-10-13 08:17 UTC, ndemidovich-sc requested changes

2022-10-13 08:17 UTC, ndemidovich-sc commented on src/providers/DataSyncProvider.tsx
> +  }, [status?.blockSyncer.status])
I don't think that it is right way. For example, we synchronized node, but in 10 minutes it's begin sync again.

2022-10-13 12:18 UTC, skylarrichard123 approved these changes

2022-10-19 04:52 UTC, ndemidovich-sc approved these changes

2022-10-19 09:26 UTC, merged